version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: rollup
    versions:
    - ">= 2.18.a, < 2.19"
  - dependency-name: rollup-plugin-visualizer
    versions:
    - "> 4.2.0, < 5"
  - dependency-name: rollup-plugin-visualizer
    versions:
    - 5.2.0
    - 5.3.0
    - 5.3.3
    - 5.3.6
  - dependency-name: husky
    versions:
    - 5.1.3
  - dependency-name: svelte
    versions:
    - 3.32.1
    - 3.32.3
